---
- name: collect commands
  block:
    - name: run command
      command: "{{ object }}"
      changed_when: no
      register: forensics_run_command
    - name: save output
      copy:
        content: "{{ forensics_run_command.stdout }}"
        dest: "{{ forensics_local_storage_path }}/{{ object | replace(' ','-') }}"
      delegate_to: localhost
      changed_when: no
  rescue:
    - name: rescue when command failed.
      debug:
        msg: "Could not collect command"
