---
- name: run command
  command: "{{ object.command }}"
  changed_when: no
  register: forensics_run_command

- name: save output
  copy:
    content: "{{ forensics_run_command.stdout }}"
    dest: "{{ forensics_local_storage_path }}/{{ object.destination }}"
  delegate_to: localhost
