---
# tasks file for forensics
- name: create forensics_local_storage_path
  file:
    path: "{{ forensics_local_storage_path }}"
    state: directory
    mode: "0700"

- name: collect files in directories
  include_tasks: directory_collector.yml
  loop: "{{ forensics_directory_list }}"
  loop_control:
    loop_var: object

- name: collect files
  include_tasks: file_collector.yml
  loop: "{{ forensics_file_list }}"
  loop_control:
    loop_var: object

- name: collect command output
  include_tasks: command_collector.yml
  loop: "{{ forensics_command_list }}"
  loop_control:
    loop_var: object

# - name: collect history
# - name: collect authorized keys
