---
# tasks file for forensics

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: create {{ forensics_local_storage_path }}/{{ inventory_hostname_short }}
  file:
    path: "{{ forensics_local_storage_path }}/{{ inventory_hostname_short }}"
    state: directory
    mode: "700"

- name: collect files in directories
  include_tasks: directory_collector.yml
  loop: "{{ forensics_directory_list }}"
  loop_control:
    loop_var: object

- name: collect files
  include_tasks: file_collector.yml
  loop: "{{ forensics_file_list }}"
  loop_control:
    loop_var: object

- name: collect command output
  include_tasks: command_collector.yml
  loop: "{{ forensics_command_list }}"
  loop_control:
    loop_var: object

- name: collect specific files in directories
  include_tasks: specific_file_collector.yml
  loop: "{{ forensics_specific_file_list }}"
  loop_control:
    loop_var: object
